FROM himankj09/pytorch-cpu-lite:latest

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p /app/data/input /app/data/output /app/checkpoints /app/logs
ENV PYTHONUNBUFFERED=1

CMD ["python", "src/infer.py"]